
#BUILD
FROM node:22-alpine AS build
WORKDIR /app
COPY web/package*.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

#DEVELOPMENT
FROM node:22-alpine AS development             
WORKDIR /app
COPY web/package*.json ./
RUN npm ci
COPY web/ .
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]