# BUILD
FROM node:22-alpine AS build
WORKDIR /app
COPY api/package*.json ./
RUN npm ci
COPY api/ ./
RUN npm run build

# DEVELOPMENT
FROM node:22-alpine AS development
WORKDIR /app
COPY api/package*.json ./
RUN npm ci
COPY api/ .
EXPOSE 8000
CMD ["npm", "run", "start:dev"]