server {
    listen 3000;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Проксирование API-запросов на бэкенд
    location /api/ {
        proxy_pass http://host.docker.internal:8000;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}